### PR TITLE
Revamp frontend UI for sign up/ log in

### PR DESCRIPTION
**Pull request by Punpun1643**
## Refactoring

- Putting everything in one file make it difficult to change styling as components are not abstracted out. Let's abstract out components to make it more OOP and make it more reusable.
- This also allows for easier styling later on.

## UI changes
- [x] Add hyperlink to switch to login at signup
- [x] Add hyperlink to switch to signup at login
- [x] Add dynamic checks for password conditions (will only show if the condition does not satisfy)
- [x] Fix snackbar for better UI
- [x] Fix error alert for better UI
- [x] Fix success alert for better UI

## Demo
- Sign up page
Demo vid: https://drive.google.com/file/d/1uYl6Z0WlFEQl8ggaONKhab6qUdudnKt7/view?usp=sharing

6FAB5CB7-E086-4035-88D3-96EF75ED0130

- Login

EABA54CF-4201-4AD4-AF6C-9961F174C425

- Snackbar upon error 

BB7EB869-E710-40A3-B018-8A2C8CAB4EB7

- Dynamic checks for signup password field

1960749B-AA2F-4BBF-972B-923F85A5E3C4

- Alerts related to errors

68922394-75C5-4AB1-B494-0566739B841C

0CFC5C24-7F70-479B-9D3D-6ED5C9115AC5

C0ADC4D0-CCA7-45A8-A944-5CF304C2638C

- Alerts related to successes

4F46E6A9-BE08-4B68-B47C-F10DC50C6E3C

### CODE REVIEW

**Comment by Punpun1643** [comment]
PR still in progress but I think can check for those screenshots first. Should be mainly for sanity check since this PR involves some refactoring to make it easier to do component styling.

**Review by ureshiiYing — COMMENTED** [review]
Tested, generally looks good! (ignoring styling first and looking at refactoring of code)

**Review by fantablack — COMMENTED** [review]
I like the way you refactored the different components so that they are now actually reusable. Thanks for showing us a good way to do so.

**Review by dionegoh — APPROVED** [review]
tested, LGTM!

**Pull request merged**
