### PR TITLE
Update username handling from using Session to Cookies

### LINKED ISSUE #94: Individualized FE pages crash when navigating directly via their URL
* Individualized FE pages such as `Home` depend on username passed via navigation state
* This causes the FE to crash when navigating directly to it via its URL manually

### PR DESCRIPTION
**Pull request by fantablack**
Fixes #94 

**Summary**
* ~~Update useSessionStorage() to use a default string value rather than navigate() params~~
* Update username read/write to use cookies instead of storage
* Pages updated with this new functionality in this PR: `Home` and `ChangePassword`

**Steps to test**
1. `npm install` in the frontend directory
2. Perform a login in the frontend
3. Manually type out `http://localhost:3000/home` in the URL bar and hit enter
4. Expected result: the home page renders without crashing. (It would be a white screen before this fix). A cookie 'username' is present on the browser that supplies the username to the application.

### CODE REVIEW

**Comment by ureshiiYing** [comment]
@fantablack , you made the PR to wrong branch

**Comment by fantablack** [comment]
Good catch! Updated to point to `user-service` branch

**Comment by ureshiiYing** [comment]
This issue occurs:

After logging in as `may`, the `setSessionUsername` does not finish executing before `navigate` to `\home` finishes:
image

image

**Comment by fantablack** [comment]
Updated username read/write to use cookies instead of storage, will not run into issues such as username not saved to session before navigation

**Review by ureshiiYing — APPROVED** [review]
Tested, and works as expected. No issue with setting username while using the cookie. Other user-service features works as before. Great job! LGTM!

**Pull request merged**
