### PR TITLE
Set up yjs and bind it to editor

### LINKED ISSUE #97: Flickering issues in code editor when there are too many changes happening

### PR DESCRIPTION
**Pull request by dionegoh**
Fixes #97 

To fix the flickering bug, we cannot use the idea of emitting the whole text to the server upon each keypress, because of its high overhead

Summary of changes made 
- set up yjs, webrtc connection and bind it to quill editor 
- ensured that text won't flicker anymore and user can type at a fast speed  
- added css styling so that the lines are numbered 

reason for using yjs:
- it handles the backend and complex algorithm of people editing the same text at the same time 
- lightweight : don't have to run anything on the server, implement it on frontend will do

to test:
- cd to `matching-service` and run `node index`
- cd to frontend and run `npm i` before running `npm start` 

more information on yjs can be found here: https://docs.yjs.dev/getting-started/a-collaborative-editor

### CODE REVIEW

**Comment by Punpun1643** [comment]
I think looks good, maybe we could try to work on the editor UI for this PR also. 

Another *possible* problem is for now we can't see the cursor for both users, so actually it may cause duplicate edits. 

But yup bug is resolved! 👍🏻

**Comment by Punpun1643** [comment]
15B7E0FD-1ACE-4246-97AE-606245A3DB03

**Comment by Punpun1643** [comment]
Demo link: https://drive.google.com/file/d/1krh0JnCwgHWxHjN5o8kfNhh_VLPyVmzt/view?usp=sharing

Not in the video but I tested refreshing and works fine!

@dionegoh  From the demo link, the UI is kinda not wrapped properly. I think we should fix this ah cuz we will likely do split screen during demo. It will be quite obvious 😅

I think can fix the UI in other PR with other UI issues :D

**Comment by Punpun1643** [comment]
Oh another thing is I'm using roomId as the cursor filed (colour thing for cursor identifier).

```javascript
awareness.setLocalStateField("user", {
          // using roomId now. possibly can change to something better.
          name: `${roomId}`,
          color: color,
        });
```

Technically it doesn't really matter much cuz there are 2 users anyway so technically we don't really need a label to identify who the user is. 

But guess its a nice UI thing if we could identify users as something like 'User 1' & 'User 2'. Possibly can pass socket ids as props from `RoomPage.js` but haven't really think about that haha. But this is fine for now :D

**Review by Punpun1643 — APPROVED** [review]

**Comment by dionegoh** [comment]
> Oh another thing is I'm using roomId as the cursor field (colour thing for cursor identifier).
> 
> ```js
> awareness.setLocalStateField("user", {
>           // using roomId now. possibly can change to something better.
>           name: `${roomId}`,
>           color: color,
>         });
> ```
> 
> Technically it doesn't really matter much cuz there are 2 users anyway so technically we don't really need a label to identify who the user is (i.e. can use something like 'another user' too).
> 
> But guess its a nice UI thing if we could identify users as something like 'User 1' & 'User 2'. Possibly can pass socket ids as props from `RoomPage.js` but haven't really think about that haha. But this is fine for now, just letting you know in case I forget :D

Yup maybe in the future we can get the names of the users from the `user-service` side and use that as cursor identifier

Tested and it works! :-) will work on the UI changes

**Pull request merged**
