### PR TITLE
Implement chat service

### LINKED ISSUE #111: Chat service implementation

### PR DESCRIPTION
**Pull request by Punpun1643**
Fixes #111 

To test:
- run all services
- `cd` to chat-service
- `npm run dev`
- try sending messages should work
- messages should only be updated within users in the same room

Demo vid: https://drive.google.com/file/d/1jkYnFbKVhqU7CVj9jfEp3-WjnfXUMHDf/view?usp=sharing

B3AB6639-A29A-4205-ADD4-71402CDAB830

64653213-17C3-4F41-9D19-28D3CF40F0E1

### CODE REVIEW

**Comment by Punpun1643** [comment]
UX improvment

- [ ] Auto-scroll
- [ ] Identify ownership of chat
- [ ] Empty input box on submit

**Comment by Punpun1643** [comment]
Demo vid: https://drive.google.com/file/d/1jkYnFbKVhqU7CVj9jfEp3-WjnfXUMHDf/view?usp=sharing

**Comment by Punpun1643** [comment]
@CS3219-AY2223S1/g12 Mainly for sanity check as well before merging

**Review by dionegoh — APPROVED** [review]
Tested and works well. LGTM! :)

**Review by ureshiiYing — APPROVED** [review]
Tested, and generally works well!

A few things:
image

- Might want to consider setting a min width, height to prevent users from being able to do that ^

- Consider using material ui components, so that the style is consistent throughout the page

These are just some style changes, that could be addressed later. LGTM!

**Comment by Punpun1643** [comment]
@ureshiiYing Thanks for review! Sorry don't really get it, what do you mean by 'being able to do that'?

**Pull request merged**
