### PR TITLE
Create socket.io client instance when find match button is clicked 

### LINKED ISSUE #4: Socket.io Client

### PR DESCRIPTION
**Pull request by dionegoh**
Fixes #4 , #37

Summary: 
- Currently, there is no connection between the frontend views and backend 
- This PR creates a socket.io client to connect to the socket.io server whenever a match button is clicked 
- This PR also routes the user to the countdown timer the match button is clicked 

Whenever a match button is clicked, a socket.io client is instantiated and emits the event 
image

The server receives it and logs the event onto the console 
image

How to test:
- cd to `matching-service` and run `node index.js`
- open a new terminal
- cd to `frontend` and run `npm start` (run `npm install` beforehand to install dependencies)
- navigate to `http://localhost:3000/selectquestiondifficulty`
- click on a button
- check that you are routed to the countdown timer 
- go back to the matching service page and look at the console logs to check if event has been received by server

### CODE REVIEW

**Comment by ureshiiYing** [comment]
Tested and works. Only one issue -  I tried to connect but forgot to run `matching-service`. After I ran `matching-service`, it received 2 requests. Is that intended behaviour?

**Comment by dionegoh** [comment]
> Tested and works. Only one issue - I tried to connect but forgot to run `matching-service`. After I ran `matching-service`, it received 2 requests. Is that intended behaviour?

@ureshiiYing hmmm I don't think so! I went to run frontend first before running backend and still only received one request! 
However, when I run frontend and click a FindMatch button, then run backend and click the FindMatch button again, the server received the request emitted from both buttons!

**Comment by ureshiiYing** [comment]
> > Tested and works. Only one issue - I tried to connect but forgot to run `matching-service`. After I ran `matching-service`, it received 2 requests. Is that intended behaviour?
> 
> @ureshiiYing hmmm I don't think so! I went to run frontend first before running backend and still only received one request! However, when I run frontend and click a FindMatch button, then run backend and click the FindMatch button again, the server received the request emitted from both buttons!

Ok! Same result then. Think this issue can be addressed later, I'll approve the PR first :)

**Review by ureshiiYing — APPROVED** [review]
LGTM!

**Review by Punpun1643 — APPROVED** [review]

**Pull request merged**
