### PR TITLE
Implement FE route protections

### LINKED ISSUE #115: Certain routes in FE should only be accessible by logged in users
Routes that require protection:
* `selectquestiondifficulty`
* `roompage`
* `home`
* `logout`
* `changePassword`
* `deleteAccount`

### PR DESCRIPTION
**Pull request by fantablack**
Fixes #115 

**Summary**
Add protections (redirection to `/login` if not logged in) to the following pages:
* `selectquestiondifficulty`
* `roompage`
* `home`
* `logout`
* `changePassword`
* `deleteAccount`

### CODE REVIEW

**Review by ureshiiYing — COMMENTED** [review]
Seems like the `ensureLoggedIn` function is the same for all the pages. Perhaps you can extract them into a new common functions .js file (eg. name it common.js), and call the function from there instead? This is to reduce duplication of code.

**Comment by fantablack** [comment]
@ureshiiYing Good for pointing that out! I actually tried doing so but to no avail, due to the following reasons:

Note:
This PR has several instances of DRY violations, but that is an acknowledged design choice due to the following reasons:
1. I first put it as a shared custom hook, but react doesn't allow us to call a custom hook in the useEffect hook.
2. When I tried packaging the function in a common Util.js, I couldn't place the navigate('\login') in the export function as I needed to get that navigate by first calling useNavigation() on each page. In addition React disallowed me from using navigate() in a non-hook function.

**Comment by ureshiiYing** [comment]
I found a way to extract out the function to reduce code duplication. Hope it helps!

**Comment by fantablack** [comment]
> I found a way to extract out the function to reduce code duplication. Hope it helps!

@ureshiiYing Fantastic! Updated the PR to use the extracted method. Thanks!

**Review by ureshiiYing — APPROVED** [review]
Tested and works! LGTM!

**Pull request merged**
